### ISSUE TITLE
Row-wise combine of Coe objects

### ISSUE THREAD

**Issue by MikePapaWhisky** [MomX/Momocs#203]
Any word on the implementation (as hinted in `?combine`) of row-wise, or preferably choice between row-wise and column-wise, combining of Coe objects? Would be useful when calculating mshapes (which must be done on Coe) are then combining mshapes with other shapes.

_E.g. might expect the following to re-create `bot_coe`_
```
bot_coe <- bot %>% efourier(nb.h = 2, norm = F)
bot_coe_whi <- bot_coe %>% Momocs::filter(type == "whisky")
bot_coe_bee <- bot_coe %>% Momocs::filter(type == "beer")
Momocs::combine(bot_coe_whi, bot_coe_bee)```

**Comment by MikePapaWhisky** [comment]
Guess it depends on whether '_combine row-wise_' and '_combine column-wise_' are going to be two separate functions, or argument options of a single function. Assuming the former...

I haven't found any use for '_combine column-wise_' (not to suggest I don't think there are perfectly worthwhile ones), so its tricky to think of a succinct name for it.

For '_combine row-wise_' the most obvious suggestion for me would be `merge`. Otherwise, and in Tidyverse parlance, `bind_rows` would be the nearest comparison. It would be handy if differences in `$fac` between the two objects being merged could be handled, making it something like `dplyr::full_join`. Maybe `join`?

**Comment by vbonhomme** [comment]
* combine column-wise is typically used when 2+ views are combined into the same Coe.
 * `bind_rows/cols` would be nice but they would only make sense when one have a very good understanding of what's going on (which is desirable but not the rule). `merge` is already used in base R.

Based on [this], what do you think of:
 * `tie` for row-wise (it carries the idea of binding two _long_ stuff together isn't ?)
 * `couple` for column-wise (same with the idea of joining similar stuff together but more side-wise just like a couple in real life?)

what do your English ears/brain/heart think of that?

**Comment by MikePapaWhisky** [comment]
(Yeah, silly of me to forget use of column-wise combine).

Both are essentially 'to _concatenate_', though not sure which direction more appropriate for that word. 

Like `tie`, but `stitch` might be better ('tie' has a plethora of meanings in English). Also, though, maybe `append` (as you're appending data onto data). 

`couple` is good too but might imply the two are kept separate. Other ideas `hinge` and `unite`/`unify` (both of imply bringing together similar things).

Discussed around office, `append` and `unite` preferred.

**Comment by vbonhomme** [comment]
`append` is also a R base function but sounds good. I think this could be just `c` (which is short for concatenate as well).

`unite` is nice but the contrary operation already exist in Momocs (dissolve). `gather` is already taken, what about `assemble`?

otherwise what do you think of `superimpose` and `juxtapose`. It's perfectly understood by frog people but do you guys use it a lot too? Pretty long though.

----

side comment, this conversation is a pretty good confirmation of [this](https://martinfowler.com/bliki/TwoHardThings.html)

**Comment by MikePapaWhisky** [comment]
`juxtapose` sounds good (you could have `appose` too) for the _combine column-wise_ function - i.e. to place side-by-side.

'superimpose' not so good as means to place on top of each other, and these functions are for joining things together. 

`assemble` doesn't feel right to me (lacks direction). How about its synonyms `convene`, `accumulate` or even `bunch'. 

Whatever you think is best, frog ears are better than beef ears anyway.

**Comment by vbonhomme** [comment]
I think I'll let `combine` for column-wise and create a `c` method for row-wise

**Comment by vbonhomme** [comment]
Is now, natively, solved in [Momocs2](https://momx.github.io/Momocs2)
