### ISSUE TITLE
coo_centsize: 'mean(sqrt(...'

### ISSUE THREAD

**Issue by Almond-S** [MomX/Momocs#208]
Hi Vincent,
firstly, thanks for providing that amazing package!!!
In the function `coo_centsize.default`, I wonder about your defintion of the centroid size:
https://github.com/MomX/Momocs/blob/2e18272432f94164060b4d068dcb6f12d55f16e3/R/coo-utilities.R#L2507
I would have expected `sqrt(mean(...` instead of `mean(sqrt(...` as this would correspond to the defintion of Dryden and Mardia 2012 (times constant) and to what I'd consider standard in shape analysis. Sorry, if I'm wrong, but is this maybe supposed to be the other way?
Thanks and cheers,
Almond

**Comment by vbonhomme** [comment]
Hi Almond
You're right, thanks a lot.
In my everyday work I almost never use it (just like pretty much everything landmarks), so I'm glad you're here ;-)
I'm reviewing all Momocs these days and I have to resubmit a version soon, so I'll correct it.
best

**Comment by Almond-S** [comment]
Oh perfect, thank you, and thanks for your quick reply!

**Comment by vbonhomme** [comment]
See https://momx.github.io/Momocs2/reference/get_centsize.html
