### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cynthiafannn** [MomX/Momocs#209]
Hi there,
I'm struggling to install Momocs via a server. The version of R is 3.6.2 and the error message I get is "installation of package had a non-zero exit status". 
Would this be caused by the version of R?
Thank you!

**Comment by vbonhomme** [comment]
Yep. Im on it...

**Comment by petrpajdla** [comment]
Hi cynthiafannn,
I guess you installed from github with `devtools::install_github("MomX/Momocs")`, right?
Momocs is available for R 3.6.2, there are probably some other dependencies missing. Now this quite depends on your system, with Debian 9 I had a problem in dependencies of package `rgl`, installing missing library solved it for me.
Are you on Windows or Linux?

**Comment by cynthiafannn** [comment]
HI there!

So I followed this:
sudo apt-get install xorg
sudo apt-get install libx11-dev
sudo apt-get install libglu1-mesa-dev
install.packages("rgl", dependencies = TRUE)
sudo apt-get install r-cran-rgl
And managed to get it installed again.

Thank you for responding!

Really appreciate it!

Cynthia

On 04 Mar 2020, at 15:56, Petr Pajdla <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi cynthiafannn,
I guess you installed from github with devtools::install_github("MomX/Momocs"), right?
Momocs is available for R 3.6.2, there are probably some other dependencies missing. Now this quite depends on your system, with Debian 9 I had a problem in dependencies of package rgl, installing missing library solved it for me.
Are you on Windows or Linux?
