### ISSUE TITLE
Issue creating object from fgProcrustes

### ISSUE THREAD

**Issue by Lauraaas** [MomX/Momocs#215]
Hi,

I have been having issues creating an object from the fgProcrustes function. The GPA is carried out and produces a graph however I cannot create an object from it to use in the PCA. Here is some example code:

winggpa <- fgProcrustes(wings, tol=0.1) %>% stack()
iteration:  1 	gain: 53084 
iteration:  2 	gain: 0.1323 
iteration:  3 	gain: 0.056732 
will soon be deprecated, see ?pile
>  wingpca <- PCA(winggpa)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

The object 'winggpa' is Null (empty) so cannot be selected for use in other functions, I am not sure if there is something  I am missing or perhaps a bug. 

This is using R3.6.3 and a fresh install of MOMOCS from Github. Any advice is much appreciated.

**Comment by vbonhomme** [comment]
Are you sure winggpa is really null? If not could you please send it to me
with save()

**Comment by Lauraaas** [comment]
Yes, in the values section of global environment it is listed as NULL. 

<img width="488" alt="Screenshot 2021-01-20 at 11 35 11" src="https://user-images.githubusercontent.com/63308112/105169605-aa9f3980-5b13-11eb-95df-8b964b7fd84a.png">
