### ISSUE TITLE
Run efourier directly on coordinate within a dataframe

### ISSUE THREAD

**Issue by JohnSal1** [MomX/Momocs#221]
I will start with a praise; it is a wonderful package that I only discovered few days ago. 
My issue: I have field within a dataframe (e.g., mydata[2,2]) that describe closed object coordinates in this format X Y, X1 Y1, … Xn Yn. How can I run the efourier directly on this field?

**Comment by vbonhomme** [comment]
Sth around mutate(yourdf, coef=map(yourcol, efourier)).
Cant check im afk for a month
All the best

**Comment by JohnSal1** [comment]
Correcting my issue question, how to convert this closed object coordinates field to a list or a matrix of coordinates or a Out object so I can input them into the efourier command

**Comment by vbonhomme** [comment]
Out(yourdf$yourcol, select(yourdf, -yourcol))

**Comment by JohnSal1** [comment]
I am still struggling even in creating this Out object based on this simple code:
```
library(Momocs)

Obj1Fac <- as.data.frame(c("Temp"))
Obj1Matrix <- (matrix(1:10, ncol=2))
Obj1Matrix <- coo_close(Obj1Matrix)
Obj1 <- Out(Obj1Matrix, Obj1Fac) 
```
I get this `Error in 1:k : NA/NaN argument`

Why?

**Comment by vbonhomme** [comment]
Obj1matrix must be a list. See ?Out

**Comment by JohnSal1** [comment]
Thanks
